docs: reference terraform & docs.
acep-devops/tf-github pull request #18
Opened 2022-07-14 19:47 UTC by dayne

While reading README realized I wanted reference to terraform & the github provider docs handy.

2022-07-14 23:33 UTC, dgpalmieri requested changes

2022-07-14 23:33 UTC, dgpalmieri commented on README.md
> +This repo manages the ACEP DevOps Organization using [terraform](terraform.io)'s [github provider integration]https://registry.terraform.io/providers/integrations/github/latest/docs)
Needs an opening parenthesis on the last link.

2022-07-15 00:08 UTC, dgpalmieri commented
Updated to pass style checks

2022-07-15 00:21 UTC, TechSolomon requested changes
Link to https://www.terraform.io/ is broken?

2022-07-15 00:25 UTC, dgpalmieri commented
weird, the link worked fine for me. Probably good to have the rest of the window dressing though

2022-07-15 00:25 UTC, dgpalmieri approved these changes
who knew that this pr would take so long

2022-07-15 00:31 UTC, TechSolomon approved these changes
:shipit:

2022-07-15 00:35 UTC, merged